import { DataSource } from "typeorm";
import {
  User,
  Address,
  Restaurant,
  Category,
  MenuItem,
  MenuItemImage,
  Cart,
  Order,
  OrderItem,
  RestaurantAdmin,
  OrderStatusHistory,
  Delivery,
  RatingReview,
  ReviewResponse,
} from "./entity/index";

export const AppDataSource = new DataSource({
  type: "mysql",
  host: process.env.DATABASE_HOST || "",
  port: process.env.DATABASE_PORT as unknown as number,
  username: process.env.DATABASE_USERNAME || "",
  password: process.env.DATABASE_PASSWORD || "",
  database: process.env.DATABASE_NAME || "",
  synchronize: true,
  logging: false,
  entities: [
    User,
    Address,
    Restaurant,
    Category,
    MenuItem,
    MenuItemImage,
    Cart,
    Order,
    OrderItem,
    RestaurantAdmin,
    OrderStatusHistory,
    Delivery,
    RatingReview,
    ReviewResponse,
  ],
});
